name: Secret Scan

on:
  pull_request:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Detect secrets
        uses: dennis714/detect-secrets-action@main
        with:
          baseline: '.secrets.baseline'
